//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGRLF.MainWeb.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PGRLF.MainWeb.Forms.FormResources", typeof(FormResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prohlašuji, že údaje uvedené v této žádosti o podporu Podpůrného garančního rolnického a lesnického fondu, a.s. a v jejích přílohách jsou pravdivé a že splňují všechny obecné podmínky pro poskytnutí Podpory. Jsem si vědom/vědoma právních následků případného uvedení nepravdivých nebo neúplných údajů.
        ///&lt;br&gt;&lt;br&gt;
        ///Prohlašuji, že k níže uvedenému datu nemá žadatel nedoplatky vůči Státnímu zemědělskému intervenčnímu fondu, Ministerstvu zemědělství nebo vůči Státnímu pozemkovému úřadu. Svým podpisem zároveň poskyt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CestneProhlaseni {
            get {
                return ResourceManager.GetString("CestneProhlaseni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo účtu obsahuje nepovolené znaky nebo je ve špatném formátu.
        /// </summary>
        public static string Chyba_CisloUctu {
            get {
                return ResourceManager.GetString("Chyba_CisloUctu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum je v chybném formátu.
        /// </summary>
        public static string Chyba_DatumNarozeni {
            get {
                return ResourceManager.GetString("Chyba_DatumNarozeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Špatný formát DIČ.
        /// </summary>
        public static string Chyba_DIC {
            get {
                return ResourceManager.GetString("Chyba_DIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Špatný formát IČ.
        /// </summary>
        public static string Chyba_IC {
            get {
                return ResourceManager.GetString("Chyba_IC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum je v chybném formátu.
        /// </summary>
        public static string Chyba_ORDatum {
            get {
                return ResourceManager.GetString("Chyba_ORDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum je v chybném formátu.
        /// </summary>
        public static string Chyba_ProdejPodnikuDatum {
            get {
                return ResourceManager.GetString("Chyba_ProdejPodnikuDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ musí obsahovat 5 číslic.
        /// </summary>
        public static string Chyba_PSC {
            get {
                return ResourceManager.GetString("Chyba_PSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodné číslo musí být ve tvaru ------/---- a smí obsahovat pouze číslice.
        /// </summary>
        public static string Chyba_RodneCislo {
            get {
                return ResourceManager.GetString("Chyba_RodneCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonní číslo nebo fax musí obsahovat 9 číslic.
        /// </summary>
        public static string Chyba_Telefon {
            get {
                return ResourceManager.GetString("Chyba_Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum je v chybném formátu.
        /// </summary>
        public static string Chyba_UkonceniCinnostiDatum {
            get {
                return ResourceManager.GetString("Chyba_UkonceniCinnostiDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientační číslo.
        /// </summary>
        public static string CisloOrientacni {
            get {
                return ResourceManager.GetString("CisloOrientacni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo popisné.
        /// </summary>
        public static string CisloPopisne {
            get {
                return ResourceManager.GetString("CisloPopisne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo účtu.
        /// </summary>
        public static string CisloUctu {
            get {
                return ResourceManager.GetString("CisloUctu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZ-NACE (hlavní činnosti).
        /// </summary>
        public static string CZNACE {
            get {
                return ResourceManager.GetString("CZNACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum narození.
        /// </summary>
        public static string DatumNarozeni {
            get {
                return ResourceManager.GetString("DatumNarozeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žadatel o podporu se považuje za propojený** s jinými podniky, pokud i tyto subjekty mezi sebou mají některý z následujících vztahů: 
        ///&lt;br&gt;
        ///a) jeden subjekt vlastní více než 50 % hlasovacích práv, která náležejí akcionářům nebo společníkům, v jiném subjektu; 
        ///&lt;br&gt;
        ///b) jeden subjekt má právo jmenovat nebo odvolat více než 50 % členů správního, řídícího nebo dozorčího orgánu jiného subjektu; 
        ///&lt;br&gt;
        ///c) jeden subjekt má právo uplatňovat více než 50% vliv v jiném subjektu podle smlouvy uzavřené s daným subjek [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeMinimis2 {
            get {
                return ResourceManager.GetString("DeMinimis2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to potvrzuje, že výše uvedené údaje jsou přesné a pravdivé a jsou poskytovány dobrovolně;
        ///&lt;br&gt;&lt;br&gt;
        ///se zavazuje k tomu, že v případě změny předmětných údajů v průběhu administrativního procesu poskytnutí podpory de minimis bude neprodleně informovat poskytovatele dané podpory o změnách, které u něj nastaly;
        ///&lt;br&gt;&lt;br&gt;
        ///&lt;b&gt;Prohlášení ke zpracování osobních údajů&lt;/b&gt;
        ///Souhlasím se zpracováním osobních údajů obsažených v tomto prohlášení ve smyslu zákona č. 101/2000 Sb., o ochraně osobních údajů, ve znění p. p.,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DeMinimis5 {
            get {
                return ResourceManager.GetString("DeMinimis5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IČ / Datum narození.
        /// </summary>
        public static string DeMinimisIC {
            get {
                return ResourceManager.GetString("DeMinimisIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obchodní jméno / Jméno žadatele.
        /// </summary>
        public static string DeMinimisName {
            get {
                return ResourceManager.GetString("DeMinimisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sídlo / Adresa žadatele.
        /// </summary>
        public static string DeMinimisSidlo {
            get {
                return ResourceManager.GetString("DeMinimisSidlo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daňové identifikační číslo.
        /// </summary>
        public static string DIC {
            get {
                return ResourceManager.GetString("DIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doba podnikání v letech.
        /// </summary>
        public static string DobaPodnikani {
            get {
                return ResourceManager.GetString("DobaPodnikani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkce.
        /// </summary>
        public static string Funkce {
            get {
                return ResourceManager.GetString("Funkce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fyzická osoba.
        /// </summary>
        public static string FyzickaOsoba {
            get {
                return ResourceManager.GetString("FyzickaOsoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .
        /// </summary>
        public static string Helpers_PrependEmptyItem__Text {
            get {
                return ResourceManager.GetString("Helpers_PrependEmptyItem__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikační číslo osoby.
        /// </summary>
        public static string IC {
            get {
                return ResourceManager.GetString("IC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kód banky.
        /// </summary>
        public static string KodBanky {
            get {
                return ResourceManager.GetString("KodBanky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj.
        /// </summary>
        public static string Kraj {
            get {
                return ResourceManager.GetString("Kraj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Křestní jméno.
        /// </summary>
        public static string KrestniJmeno {
            get {
                return ResourceManager.GetString("KrestniJmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název obce / svazku obcí.
        /// </summary>
        public static string NazevSvazkuObci {
            get {
                return ResourceManager.GetString("NazevSvazkuObci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadovaná hodnota není vyplnľna.
        /// </summary>
        public static string Nevyplneno {
            get {
                return ResourceManager.GetString("Nevyplneno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněno číslo popisné.
        /// </summary>
        public static string Nevyplneno_CisloPopisne {
            get {
                return ResourceManager.GetString("Nevyplneno_CisloPopisne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněno číslo účtu.
        /// </summary>
        public static string Nevyplneno_CisloUctu {
            get {
                return ResourceManager.GetString("Nevyplneno_CisloUctu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněno datum narození.
        /// </summary>
        public static string Nevyplneno_DatumNarozeni {
            get {
                return ResourceManager.GetString("Nevyplneno_DatumNarozeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněno daňové identifikační číslo.
        /// </summary>
        public static string Nevyplneno_DIC {
            get {
                return ResourceManager.GetString("Nevyplneno_DIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněn kontaktní email.
        /// </summary>
        public static string Nevyplneno_Email {
            get {
                return ResourceManager.GetString("Nevyplneno_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněna funkce.
        /// </summary>
        public static string Nevyplneno_Funkce {
            get {
                return ResourceManager.GetString("Nevyplneno_Funkce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněno identifikační číslo osoby.
        /// </summary>
        public static string Nevyplneno_IC {
            get {
                return ResourceManager.GetString("Nevyplneno_IC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněno jméno.
        /// </summary>
        public static string Nevyplneno_Jmeno {
            get {
                return ResourceManager.GetString("Nevyplneno_Jmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není zvolena banka.
        /// </summary>
        public static string Nevyplneno_KodBanky {
            get {
                return ResourceManager.GetString("Nevyplneno_KodBanky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není zvolen kraj.
        /// </summary>
        public static string Nevyplneno_Kraj {
            get {
                return ResourceManager.GetString("Nevyplneno_Kraj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není uveden název obce / svazku obcí.
        /// </summary>
        public static string Nevyplneno_NazevSvazkuObci {
            get {
                return ResourceManager.GetString("Nevyplneno_NazevSvazkuObci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněno obchodní jméno.
        /// </summary>
        public static string Nevyplneno_ObchodniJmeno {
            get {
                return ResourceManager.GetString("Nevyplneno_ObchodniJmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněná obec.
        /// </summary>
        public static string Nevyplneno_Obec {
            get {
                return ResourceManager.GetString("Nevyplneno_Obec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněn datum zápisu.
        /// </summary>
        public static string Nevyplneno_ORDatum {
            get {
                return ResourceManager.GetString("Nevyplneno_ORDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněn soud, který provedl zápis.
        /// </summary>
        public static string Nevyplneno_ORVydal {
            get {
                return ResourceManager.GetString("Nevyplneno_ORVydal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněn zápis do obchodního rejstříku.
        /// </summary>
        public static string Nevyplneno_ORZapis {
            get {
                return ResourceManager.GetString("Nevyplneno_ORZapis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněn počet společníků.
        /// </summary>
        public static string Nevyplneno_PocetSpolecniku {
            get {
                return ResourceManager.GetString("Nevyplneno_PocetSpolecniku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněno přijímení.
        /// </summary>
        public static string Nevyplneno_Prijmeni {
            get {
                return ResourceManager.GetString("Nevyplneno_Prijmeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněno datum prodeje podniku.
        /// </summary>
        public static string Nevyplneno_ProdejPodnikuDatum {
            get {
                return ResourceManager.GetString("Nevyplneno_ProdejPodnikuDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněno poštovní směrovací číslo.
        /// </summary>
        public static string Nevyplneno_PSC {
            get {
                return ResourceManager.GetString("Nevyplneno_PSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněno rodné číslo.
        /// </summary>
        public static string Nevyplneno_RodneCislo {
            get {
                return ResourceManager.GetString("Nevyplneno_RodneCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je potřeba souhlasit.
        /// </summary>
        public static string Nevyplneno_Souhlas {
            get {
                return ResourceManager.GetString("Nevyplneno_Souhlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněn kontaktní telefon.
        /// </summary>
        public static string Nevyplneno_Telefon {
            get {
                return ResourceManager.GetString("Nevyplneno_Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není zvolen typ společnosti.
        /// </summary>
        public static string Nevyplneno_TypSpolecnosti {
            get {
                return ResourceManager.GetString("Nevyplneno_TypSpolecnosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněno datum ukončení činnosti.
        /// </summary>
        public static string Nevyplneno_UkonceniCinnostiDatum {
            get {
                return ResourceManager.GetString("Nevyplneno_UkonceniCinnostiDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněná ulice.
        /// </summary>
        public static string Nevyplneno_Ulice {
            get {
                return ResourceManager.GetString("Nevyplneno_Ulice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není vyplněn základní kapitál.
        /// </summary>
        public static string Nevyplneno_ZakladniKapital {
            get {
                return ResourceManager.GetString("Nevyplneno_ZakladniKapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obchodní jméno.
        /// </summary>
        public static string ObchodniJmeno {
            get {
                return ResourceManager.GetString("ObchodniJmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obec.
        /// </summary>
        public static string Obec {
            get {
                return ResourceManager.GetString("Obec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum vydání.
        /// </summary>
        public static string ORDatum {
            get {
                return ResourceManager.GetString("ORDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vydal.
        /// </summary>
        public static string ORVydal {
            get {
                return ResourceManager.GetString("ORVydal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zápis do obchodního rejstříku.
        /// </summary>
        public static string ORZapis {
            get {
                return ResourceManager.GetString("ORZapis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet společníků.
        /// </summary>
        public static string PocetSpolecniku {
            get {
                return ResourceManager.GetString("PocetSpolecniku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankovní spojení (název, adresa).
        /// </summary>
        public static string PodporaZemedelec_BankovniSpojeni {
            get {
                return ResourceManager.GetString("PodporaZemedelec_BankovniSpojeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čestné prohlášení.
        /// </summary>
        public static string PodporaZemedelec_CestneVyhlasenie {
            get {
                return ResourceManager.GetString("PodporaZemedelec_CestneVyhlasenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Činnost (viz. z OR).
        /// </summary>
        public static string PodporaZemedelec_Cinnost {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Cinnost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte číslo bankovního účtu žadatele.
        /// </summary>
        public static string PodporaZemedelec_CisloBankovnihoUctu {
            get {
                return ResourceManager.GetString("PodporaZemedelec_CisloBankovnihoUctu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo účtu.
        /// </summary>
        public static string PodporaZemedelec_CisloUctu {
            get {
                return ResourceManager.GetString("PodporaZemedelec_CisloUctu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum prodeje.
        /// </summary>
        public static string PodporaZemedelec_Datum_prodeje {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Datum_prodeje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum narození.
        /// </summary>
        public static string PodporaZemedelec_DatumNarozeni {
            get {
                return ResourceManager.GetString("PodporaZemedelec_DatumNarozeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum ukončení.
        /// </summary>
        public static string PodporaZemedelec_DatumUkonceni {
            get {
                return ResourceManager.GetString("PodporaZemedelec_DatumUkonceni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum vydání osvědčení o zápisu do evidence zemědělského podnikatele.
        /// </summary>
        public static string PodporaZemedelec_DatumVydaniOsvedceni {
            get {
                return ResourceManager.GetString("PodporaZemedelec_DatumVydaniOsvedceni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIČ.
        /// </summary>
        public static string PodporaZemedelec_Dic {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Dic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte DIČ žadatele - právnické osoby.
        /// </summary>
        public static string PodporaZemedelec_DicZadatelePravnickaOsoba {
            get {
                return ResourceManager.GetString("PodporaZemedelec_DicZadatelePravnickaOsoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string PodporaZemedelec_Email {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence zemědělského podnikatele u.
        /// </summary>
        public static string PodporaZemedelec_EvidenceZemedelskehoPodnikatele {
            get {
                return ResourceManager.GetString("PodporaZemedelec_EvidenceZemedelskehoPodnikatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string PodporaZemedelec_Fax {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkce.
        /// </summary>
        public static string PodporaZemedelec_Funkce {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Funkce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IČ.
        /// </summary>
        public static string PodporaZemedelec_Ic {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Ic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte IČ žadatele - právnické osoby.
        /// </summary>
        public static string PodporaZemedelec_IcZadatelePravnickaOsoba {
            get {
                return ResourceManager.GetString("PodporaZemedelec_IcZadatelePravnickaOsoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte investiční záměr.
        /// </summary>
        public static string PodporaZemedelec_InvZamer {
            get {
                return ResourceManager.GetString("PodporaZemedelec_InvZamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je nutné zadat popis.
        /// </summary>
        public static string PodporaZemedelec_JeNutneZadatPopis {
            get {
                return ResourceManager.GetString("PodporaZemedelec_JeNutneZadatPopis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jiná výroba.
        /// </summary>
        public static string PodporaZemedelec_JinaVyroba {
            get {
                return ResourceManager.GetString("PodporaZemedelec_JinaVyroba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string PodporaZemedelec_Jmeno {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Jmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kód banky (Vyberte banku).
        /// </summary>
        public static string PodporaZemedelec_KodBankyVyberteBanku {
            get {
                return ResourceManager.GetString("PodporaZemedelec_KodBankyVyberteBanku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj.
        /// </summary>
        public static string PodporaZemedelec_Kraj {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Kraj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte kraj trvalého bydliště žadatele.
        /// </summary>
        public static string PodporaZemedelec_KrajZadatele {
            get {
                return ResourceManager.GetString("PodporaZemedelec_KrajZadatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string PodporaZemedelec_KrestniJmeno {
            get {
                return ResourceManager.GetString("PodporaZemedelec_KrestniJmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navýšení pro mladého zemědělce (do 40 let).
        /// </summary>
        public static string PodporaZemedelec_NavyseniProMladehoZemedelce {
            get {
                return ResourceManager.GetString("PodporaZemedelec_NavyseniProMladehoZemedelce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte název obce (včetně místní části) trvalého bydliště žadatele.
        /// </summary>
        public static string PodporaZemedelec_NazevObce {
            get {
                return ResourceManager.GetString("PodporaZemedelec_NazevObce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obchodní jméno.
        /// </summary>
        public static string PodporaZemedelec_ObchodniJmeno {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ObchodniJmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte obchodní jméno právnické osoby žadatele.
        /// </summary>
        public static string PodporaZemedelec_ObchodniJmenoPravnickaOsoba {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ObchodniJmenoPravnickaOsoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obec.
        /// </summary>
        public static string PodporaZemedelec_Obec {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Obec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte číslo orientační sídla právnické osoby.
        /// </summary>
        public static string PodporaZemedelec_OrientaceCisloSidlaPravnickejOsoby {
            get {
                return ResourceManager.GetString("PodporaZemedelec_OrientaceCisloSidlaPravnickejOsoby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientační číslo.
        /// </summary>
        public static string PodporaZemedelec_OrientacniCislo {
            get {
                return ResourceManager.GetString("PodporaZemedelec_OrientacniCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte číslo orientační trvalého bydliště žadatele.
        /// </summary>
        public static string PodporaZemedelec_OrientacniCisloBydliste {
            get {
                return ResourceManager.GetString("PodporaZemedelec_OrientacniCisloBydliste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plánuji prodat podnik.
        /// </summary>
        public static string PodporaZemedelec_PlanujiProdatPodnik {
            get {
                return ResourceManager.GetString("PodporaZemedelec_PlanujiProdatPodnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plánuji ukončit zemědělskou činnost.
        /// </summary>
        public static string PodporaZemedelec_PlanujuUkoncitZemedelskouCinnost {
            get {
                return ResourceManager.GetString("PodporaZemedelec_PlanujuUkoncitZemedelskouCinnost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plátce DPH.
        /// </summary>
        public static string PodporaZemedelec_PlatceDPH {
            get {
                return ResourceManager.GetString("PodporaZemedelec_PlatceDPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet společníků.
        /// </summary>
        public static string PodporaZemedelec_PocetSpolecniku {
            get {
                return ResourceManager.GetString("PodporaZemedelec_PocetSpolecniku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popisné číslo.
        /// </summary>
        public static string PodporaZemedelec_PopisneCislo {
            get {
                return ResourceManager.GetString("PodporaZemedelec_PopisneCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte číslo popisné (uváděné v katastru nemovitostí) sídla právnické osoby.
        /// </summary>
        public static string PodporaZemedelec_PopisneCisloPravnickejOsoby {
            get {
                return ResourceManager.GetString("PodporaZemedelec_PopisneCisloPravnickejOsoby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povolené znaky: + 1234567890.
        /// </summary>
        public static string PodporaZemedelec_Povolené_znaky {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Povolené_znaky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povolené znaky: 1234567890-/.
        /// </summary>
        public static string PodporaZemedelec_Povolené_znaky_Cislo_Uctu {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Povolené_znaky_Cislo_Uctu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        public static string PodporaZemedelec_Prijmeni {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Prijmeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte příjmení žadatele.
        /// </summary>
        public static string PodporaZemedelec_PrijmeniZadatele {
            get {
                return ResourceManager.GetString("PodporaZemedelec_PrijmeniZadatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ.
        /// </summary>
        public static string PodporaZemedelec_Psc {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Psc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte poštovní směrovací číslo trvalého bydliště žadatele.
        /// </summary>
        public static string PodporaZemedelec_PscABydliste {
            get {
                return ResourceManager.GetString("PodporaZemedelec_PscABydliste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte poštovní směrovací číslo sídla právnické osoby.
        /// </summary>
        public static string PodporaZemedelec_PscSidlaPravnickaOsoba {
            get {
                return ResourceManager.GetString("PodporaZemedelec_PscSidlaPravnickaOsoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodné číslo.
        /// </summary>
        public static string PodporaZemedelec_RodneCislo {
            get {
                return ResourceManager.GetString("PodporaZemedelec_RodneCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok zahájení činnosti.
        /// </summary>
        public static string PodporaZemedelec_RokZahajeniCinnosti {
            get {
                return ResourceManager.GetString("PodporaZemedelec_RokZahajeniCinnosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rostlinná výroba.
        /// </summary>
        public static string PodporaZemedelec_RostlinnaVyroba {
            get {
                return ResourceManager.GetString("PodporaZemedelec_RostlinnaVyroba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souhlas s poskytnutím osobních údajů.
        /// </summary>
        public static string PodporaZemedelec_SouhlasSPoskytnutimOsobnichUdaju {
            get {
                return ResourceManager.GetString("PodporaZemedelec_SouhlasSPoskytnutimOsobnichUdaju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splnění podmínek.
        /// </summary>
        public static string PodporaZemedelec_SplneniePodmienok {
            get {
                return ResourceManager.GetString("PodporaZemedelec_SplneniePodmienok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon 2.
        /// </summary>
        public static string PodporaZemedelec_Telefon_2 {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Telefon_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon 1.
        /// </summary>
        public static string PodporaZemedelec_Telefon1 {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Telefon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titul.
        /// </summary>
        public static string PodporaZemedelec_Titul {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Titul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titul před jménem.
        /// </summary>
        public static string PodporaZemedelec_TitulPredJmenem {
            get {
                return ResourceManager.GetString("PodporaZemedelec_TitulPredJmenem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titul za jménem.
        /// </summary>
        public static string PodporaZemedelec_TitulZaJmenem {
            get {
                return ResourceManager.GetString("PodporaZemedelec_TitulZaJmenem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ společnosti.
        /// </summary>
        public static string PodporaZemedelec_TypSpolocnosti {
            get {
                return ResourceManager.GetString("PodporaZemedelec_TypSpolocnosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Údaj je povinný..
        /// </summary>
        public static string PodporaZemedelec_UdajJePovinny {
            get {
                return ResourceManager.GetString("PodporaZemedelec_UdajJePovinny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulice.
        /// </summary>
        public static string PodporaZemedelec_Ulice {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Ulice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte číslo popisné (uváděné v katastru nemovitostí) trvalého bydliště žadatele.
        /// </summary>
        public static string PodporaZemedelec_ViewModel_PopisneCislo {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ViewModel_PopisneCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popište strukturu chovaných zvířat.
        /// </summary>
        public static string PodporaZemedelec_ViewModel_StrukturaChovanychZvirat_Popište_strukturu_chovaných_zvířat {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ViewModel_StrukturaChovanychZvirat_Popište_strukturu_chovaných_z" +
                        "vířat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popište strukturu pěstovaných plodin.
        /// </summary>
        public static string PodporaZemedelec_ViewModel_StrukturaPestovanychPlodin_Popište_strukturu_pěstovaných_plodin {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ViewModel_StrukturaPestovanychPlodin_Popište_strukturu_pěstovaný" +
                        "ch_plodin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte kontaktní e-mail žadatele. Zadávejte prosím živou a prověřenou e-mailovou adresu pro primární komunikaci s PGRLF.
        /// </summary>
        public static string PodporaZemedelec_ViewModel_TPEmail_Zadejte_kontaktní_e_mail_žadatele_KontaktniEmail {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ViewModel_TPEmail_Zadejte_kontaktní_e_mail_žadatele_KontaktniEma" +
                        "il", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte název ulice trvalého bydliště žadatele.
        /// </summary>
        public static string PodporaZemedelec_ViewModel_TPUlice_Zadejte_název_ulice_trvalého_bydliště_žadatele {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ViewModel_TPUlice_Zadejte_název_ulice_trvalého_bydliště_žadatele" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte kraj.
        /// </summary>
        public static string PodporaZemedelec_ViewModel_Zadejte_kraj {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ViewModel_Zadejte_kraj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte funkci odpovědného zástupce právnické osoby.
        /// </summary>
        public static string PodporaZemedelec_VyberteFunkciPravnickaOsoba {
            get {
                return ResourceManager.GetString("PodporaZemedelec_VyberteFunkciPravnickaOsoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte jednu možnost.
        /// </summary>
        public static string PodporaZemedelec_VyberteJednuMoznost {
            get {
                return ResourceManager.GetString("PodporaZemedelec_VyberteJednuMoznost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vydal.
        /// </summary>
        public static string PodporaZemedelec_Vydal {
            get {
                return ResourceManager.GetString("PodporaZemedelec_Vydal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte datum vydání osvědčení zemědělského podnikatele.
        /// </summary>
        public static string PodporaZemedelec_ZadajteDatumVydaniaOsvedcenia {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadajteDatumVydaniaOsvedcenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte datum zápisu právnické osoby do obchodního rejstříku.
        /// </summary>
        public static string PodporaZemedelec_ZadajteDatumZapisuPravnickejOsoby {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadajteDatumZapisuPravnickejOsoby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte evidenci zemědělského podnikatele.
        /// </summary>
        public static string PodporaZemedelec_ZadajteEvidenciZemedelskehoPodnikatele {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadajteEvidenciZemedelskehoPodnikatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte měsíc a rok, ve kterém plánujete ukončit zemědělskou činnost.
        /// </summary>
        public static string PodporaZemedelec_ZadajteMesicARokUkoncenia {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadajteMesicARokUkoncenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte název banky bankovního spojení žadatele.
        /// </summary>
        public static string PodporaZemedelec_ZadajteNazovBanky {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadajteNazovBanky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte datum narození žadatele.
        /// </summary>
        public static string PodporaZemedelec_ZadejteDatumNarozeniZadatele {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadejteDatumNarozeniZadatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte IČ žadatele - fyzické osoby.
        /// </summary>
        public static string PodporaZemedelec_ZadejteIcFyzickeOsoby {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadejteIcFyzickeOsoby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte jméno odpovědného zástupce právnické osoby.
        /// </summary>
        public static string PodporaZemedelec_ZadejteJmenoZastupceOsoby {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadejteJmenoZastupceOsoby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte křestní jméno žadatele.
        /// </summary>
        public static string PodporaZemedelec_ZadejteKrestniJmeno {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadejteKrestniJmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte měsíc a rok, ve kterém plánujete prodat zemědělský podnik.
        /// </summary>
        public static string PodporaZemedelec_ZadejteMesicARokProdeje {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadejteMesicARokProdeje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte název ulice sídla právnické osoby.
        /// </summary>
        public static string PodporaZemedelec_ZadejteNazevUliceSidlaPravnickaOsoba {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadejteNazevUliceSidlaPravnickaOsoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte název obce (včetně místní části) sídla právnické osoby.
        /// </summary>
        public static string PodporaZemedelec_ZadejteNazovObcePravnickeOsoby {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadejteNazovObcePravnickeOsoby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet společníku.
        /// </summary>
        public static string PodporaZemedelec_ZadejtePocetSpolocniku {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadejtePocetSpolocniku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte příjmení odpovědného zástupce právnické osoby.
        /// </summary>
        public static string PodporaZemedelec_ZadejtePrijmeniZastupcePravnickaOsoba {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadejtePrijmeniZastupcePravnickaOsoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte rodné číslo dddddd/ddd anebo dddddd/dddd.
        /// </summary>
        public static string PodporaZemedelec_ZadejteRodneCislo {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadejteRodneCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte rodné číslo žadatele.
        /// </summary>
        public static string PodporaZemedelec_ZadejteRodneCisloZadatele {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadejteRodneCisloZadatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte soud, u kterého je právnická osoba vedena.
        /// </summary>
        public static string PodporaZemedelec_ZadejteSoud {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadejteSoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte Spisovou značku z výpisu z obchodního rejstříku.
        /// </summary>
        public static string PodporaZemedelec_ZadejteSpisovouZnackuVypisuZRejstriku {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadejteSpisovouZnackuVypisuZRejstriku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte kontaktní telefonní číslo žadatele.
        /// </summary>
        public static string PodporaZemedelec_ZadejteTelefonniCisloZadatele {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadejteTelefonniCisloZadatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Základní kapitál (tis. Kč).
        /// </summary>
        public static string PodporaZemedelec_ZadejteZakladniKapital {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZadejteZakladniKapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Základní kapitál.
        /// </summary>
        public static string PodporaZemedelec_ZakladniKapital {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZakladniKapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zápis do obchodního rejstříku.
        /// </summary>
        public static string PodporaZemedelec_ZapisDoObchodnihoRejstriku {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZapisDoObchodnihoRejstriku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Živočišná výroba.
        /// </summary>
        public static string PodporaZemedelec_ZivocisnaVyroba {
            get {
                return ResourceManager.GetString("PodporaZemedelec_ZivocisnaVyroba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Právnická osoba.
        /// </summary>
        public static string PravnickaOsoba {
            get {
                return ResourceManager.GetString("PravnickaOsoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte činnost vykonávanou při podnikání.
        /// </summary>
        public static string PredmetPodnikani__Zadejte_činnost_vykonávanou_při_podnikání {
            get {
                return ResourceManager.GetString("PredmetPodnikani__Zadejte_činnost_vykonávanou_při_podnikání", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        public static string Prijmeni {
            get {
                return ResourceManager.GetString("Prijmeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodej podniku.
        /// </summary>
        public static string ProdejPodniku {
            get {
                return ResourceManager.GetString("ProdejPodniku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum prodeje.
        /// </summary>
        public static string ProdejPodnikuDatum {
            get {
                return ResourceManager.GetString("ProdejPodnikuDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ.
        /// </summary>
        public static string PSC {
            get {
                return ResourceManager.GetString("PSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodné číslo.
        /// </summary>
        public static string RodneCislo {
            get {
                return ResourceManager.GetString("RodneCislo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;I. Žadatel o poskytnutí podpory, jakožto fyzická osoba (dále jen jako „žadatel-fyzická osoba“),&lt;/b&gt;
        ///&lt;br&gt;&lt;br&gt;
        ///tímto dává společnosti Podpůrný a garanční rolnický a lesnický fond, a.s., IČ: 492 41 494, se sídlem Praha 8 – Karlín, Za Poříčskou branou 6/č.p. 256, PSČ 186 00 (dále jen jako „Správce“), v souladu se zákonem č. 101/2000 Sb., o ochraně osobních údajů a o změně některých zákonů, ve znění pozdějších předpisů (dále jen jako „ZOOÚ“), souhlas k tomu, aby Správce zpracovával ve své databázi veškeré j [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SouhlasSeZpracovanim {
            get {
                return ResourceManager.GetString("SouhlasSeZpracovanim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obec / svazek obcí.
        /// </summary>
        public static string SvazekObci {
            get {
                return ResourceManager.GetString("SvazekObci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telefon1 {
            get {
                return ResourceManager.GetString("Telefon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druhý telefon.
        /// </summary>
        public static string Telefon2 {
            get {
                return ResourceManager.GetString("Telefon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titul před jménem.
        /// </summary>
        public static string TitulPredJmenem {
            get {
                return ResourceManager.GetString("TitulPredJmenem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titul za jménem.
        /// </summary>
        public static string TitulZaJmenem {
            get {
                return ResourceManager.GetString("TitulZaJmenem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ společnosti.
        /// </summary>
        public static string TypSpolecnosti {
            get {
                return ResourceManager.GetString("TypSpolecnosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuální ukončené období (čtvrtletí, měsíc) s doloženými účetními výkazy.
        /// </summary>
        public static string Ucet1 {
            get {
                return ResourceManager.GetString("Ucet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhad realizovaných tržeb ke konci aktuálního období (v % ročních tržeb).
        /// </summary>
        public static string Ucet2 {
            get {
                return ResourceManager.GetString("Ucet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Průměrný počet zaměstnanců od počátku roku k aktuálnímu ukončenému období.
        /// </summary>
        public static string Ucet3 {
            get {
                return ResourceManager.GetString("Ucet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podíl největšího odběratele na celkové produkci (v %) k aktuálnímu období.
        /// </summary>
        public static string Ucet4 {
            get {
                return ResourceManager.GetString("Ucet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to za aktuální ukončené období.
        /// </summary>
        public static string Ucet5 {
            get {
                return ResourceManager.GetString("Ucet5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ke konci minulého roku.
        /// </summary>
        public static string Ucet6 {
            get {
                return ResourceManager.GetString("Ucet6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ke konci předminulého roku.
        /// </summary>
        public static string Ucet7 {
            get {
                return ResourceManager.GetString("Ucet7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukončení činnosti.
        /// </summary>
        public static string UkonceniCinnosti {
            get {
                return ResourceManager.GetString("UkonceniCinnosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum ukončení.
        /// </summary>
        public static string UkonceniCinnostiDatum {
            get {
                return ResourceManager.GetString("UkonceniCinnostiDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulice.
        /// </summary>
        public static string Ulice {
            get {
                return ResourceManager.GetString("Ulice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberete z uvedených variant.
        /// </summary>
        public static string VyberVariant {
            get {
                return ResourceManager.GetString("VyberVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Základní kapitál.
        /// </summary>
        public static string ZakladniKapital {
            get {
                return ResourceManager.GetString("ZakladniKapital", resourceCulture);
            }
        }
    }
}
